### ISSUE TITLE
Request for adding Sidecar Format Options

### ISSUE THREAD

**Issue by joshjohnson** [Dash-Industry-Forum/Watermarking#1]
We have been working to implement DASH-IF WM and we find that the proposed standard results in a very large JSON formatted sidecar file. We fear that the size of the sidecar file causes performance issues:

1. The large file size adds cold start latency: on an initial request, Edge nodes must download and parse the file while the player is waiting for a response. 
2. The JSON processing adds load on the CDN - in a distributed network, it is likely that many Edge nodes will need to fetch and process the sidecar. 
3. The large JSON file increases bandwidth consumption between the Edge nodes and origin. 

To address these issues, we propose that the standard body defines a binary format that can be used in conjunction with the JSON format.  As a proof of concept, we used the [flatbuffers](https://google.github.io/flatbuffers/) serialization format to compare file size and performance. 

**File size:** In our proof of concept, we rewrote a JSON 942 KB sidecar, referencing two hours of content (with two second segments). The same data represented as a flatbuffer was 59KB - a 94% size reduction. 

**Parsing time:** Tested in NodeJS by loading the sidecar file from disk into an array once, then looping through the following set of operations to test CPU consumption of file format processing:

1. Create a JS object from the byte array containing raw file data
2. Read the startRange of the first segment
3. Read the startRange of the last segment
4. Subtract startRange of first segment from startRange of the last segment and add the difference to a variable, confirming that the compiler is not optimizing away any operations

|  | Number of operations | Amount of time | Operations per second |
| --- | --: | --: | --: |
| JSON | 1,000 | 8,141 ms | **123** |
| Flatbuffers | 10,000,000 | 1,795 ms | **5,571,031** |

\* Tests were performed as ad-hoc tests on a development laptop and are intended to be used for a relative comparison, not absolute performance data.

We propose the binary formatted sidecar would reside on the origin at a well-known location. Edge nodes would fetch the binary sidecar and use it in place of the JSON sidecar. Alternate binary formats may be preferable, but we expect them to show roughly the same benefit.

The binary sidecar offers multiple benefits: faster load times for end users, lower load on CDNs, and lower overall bandwidth consumption from origin.

The schema used for the flatbuffers proof of concept is:
 
```
namespace Watermarking;

enum SegmentType : byte { discrete, byteranges }

struct WMPaceInfoStruct {
    pos:ushort;
    // Remove fields not used at the CDN
    //version:ubyte;
    //variant:ubyte;
    //nbpart:ubyte;
    //firstpart:bool;
    iswm:bool;
}

struct Segment {
    startRange:ulong (key);
    //if startRange of next segment can be used instead, endRange of current segment isn’t needed
    //endRange:ulong;
    WMPaceInfoObject:WMPaceInfoStruct;
}
table VariantSubPaths {
    variant:ubyte;
    subPath:string;
}
table WMPaceInfo {
    segmentType:SegmentType;
    variantSubPaths: [VariantSubPaths];
    segments:[Segment];
}
root_type WMPaceInfo;
```

**Comment by lpiron** [comment]
Agreed. Move always from JSON to Flatbuffers between Origin and Edge

**Comment by RexBelli** [comment]
Were alternative (binary) formats considered or tested as alternatives to Flatbuffers?

**Comment by RobertLabonte** [comment]
We found using JSON has performance implications for CDNs. We favor using a more efficient binary serialization format. In our testing we found FlatBuffers to offer great performance, but there were some caveats and other concerns that we feel make it not an ideal fit as a sidecar format. We favor using [MessagePack](https://msgpack.org/index.html) as the binary sidecar format because it is loosely based on JSON, does not require a schema file, has small file sizes and decoding/encoding libraries are available for most languages. 

In our assessment we benchmarked multiple serialization formats by creating WM sidecar files in 600 segment increments going up to 7200 segments. The benchmarks were performed using Rust locally on a 6-core x86_64 MacBook Pro. We tried our best to faithfully translate the existing DASH-IF JSON schema to other format schemas. Like @joshjohnson's tests, we ensured every segment was read by looping through the segments. The loop also mimics the logic required for returning the final segment which also benchmarks worst-case performance. Below are results for sidecars with 1800 segments, which equates to 1-hour of content using 2 second segments.

Format | Speed (microseconds) | Size (bytes)
-- | -- | --
JSON | 622 | 261262
FlatBuffers | 2 | 79424
FlatBuffers (checked) | 312 | 79424
Cap'n Proto | 106 | 72176
MessagePack | 148 | 46222
ProtoBuf | 161 | 44848
CBOR | 648 | 188626

As previously mentioned, we have concerns about using FlatBuffers as a sidecar format. In the chart above, there are two values for FlatBuffers: the very impressive 2 microseconds and less impressive 312 microseconds. The Rust FlatBuffers library offers two decoding functions. The faster function uses Rust's unsafe features while the slower function safety checks each value in the FlatBuffer. The FlatBuffer library recommends against using the faster function on FlatBuffers created by untrusted sources.

Below is a list of concerns regarding serialization formats that use independent schema files (FlatBuffers, Cap'n Proto and Protocol Buffers):
- If a format is chosen that requires a schema file, will DASH-IF maintain and be the source-of-truth for the schema file? 
- Is there potential for breaking changes to the schema? 
- If there is a breaking change, how would that be handled?  

Due to concerns about schema files, we favor the schema-less MessagePack serialization format over FlatBuffers, Cap'n Proto and Protocol Buffers. MessagePack offers flexibility for future sidecar changes, small file sizes and can be parsed at more than 4x the speed of JSON. MessagePack's parsing speed is comparable to Cap'n Proto and Protocol Buffers. 

It's important that any binary format option has all the features of the JSON sidecar. Removing "endRange" in sidecar segments will make delivering the last segment difficult. It can also lead to relying on backend server behavior and the possibility to "fail open" if a segments list is truncated somehow in a sidecar. 

We do believe the JSON format, and subsequently a binary sidecar format, can be made more efficient. 

Proposed Sidecar Changes:
- Limit data in sidecar to only data required by CDNs (startRange, endRange, pos)
- Remove one level of indirection, segments should be a single dictionary object to improve JSON parsing speed.
- Remove non-watermarked segments from the segments dictionary list. It's unlikely watermarked and non-watermarked will be interspersed, so make a high level field identifying at what byte position watermarking begins. All requests before the first watermarking byte position will be honored by a CDN. This would also allow for the removal of the "iswm" bool in segments list. 
- Make "version" a top level key/value, to prevent redundant reading of the same data in each segment. 
 
Example WM sidecar JSON with proposed changes:
```{
  "version": 1,
  "segmentType": "byterange",
  "iswmStartRange": 22510,
  "variantSubPaths": [
    {
      "variant": 0,
      "subPath": "a"
    },
    {
      "variant": 1,
      "subPath": "b"
    }
  ],
  "segments": [
    {
      "startRange": 22510,
      "endRange": 524067,
      "pos": 0
    },
    {
      "startRange": 524068,
      "endRange": 1024868,
      "pos": 1
    }
  ]
}
```

**Comment by lpiron** [comment]
@RobertLabonte, can you join a call on June 15, 9:00 AM for discussing your comment.

**Comment by msanmart-akamai** [comment]
> The faster function uses Rust's unsafe features while the slower function safety checks each value in the FlatBuffer. The FlatBuffer library recommends against using the faster function on FlatBuffers created by untrusted sources.
- Can you provide a reference to the recommendation? 
- Is this issue a common deserialization problem in all suported languages or just a Rust specific issue? The only reference I found is in the [Flatbuffers Rust section](https://google.github.io/flatbuffers/flatbuffers_guide_use_rust.html).

> Below is a list of concerns regarding serialization formats that use independent schema files (FlatBuffers, Cap'n Proto and Protocol Buffers):
> 
> * If a format is chosen that requires a schema file, will DASH-IF maintain and be the source-of-truth for the schema file?
- DASH-IF should be the source of truth for the schema and it should be part of the spec.

> * Is there potential for breaking changes to the schema?
> * If there is a breaking change, how would that be handled?
- The schema should be versioned and backward compatible. For example, If the a CDN logic cannot use the current version it should ignore any (new) unrecognized fields.

> Due to concerns about schema files, we favor the schema-less MessagePack serialization format over FlatBuffers, Cap'n Proto and Protocol Buffers. MessagePack offers flexibility for future sidecar changes, small file sizes and can be parsed at more than 4x the speed of JSON. MessagePack's parsing speed is comparable to Cap'n Proto and Protocol Buffers.

- We think that the schema should be part of the WmPaceInfo interface and as such it should be provided by DASH-IF specs. If the performance is an issue, based on the results presented by @RobertLabonte above, Protobuf would be the best candidate. However in many [other benchmarks](https://google.github.io/flatbuffers/flatbuffers_benchmarks.html) Flatbuffers is always orders of magnitud faster than Protobuf, specifically in deserializations.

**Comment by RobertLabonte** [comment]
@lpiron We will be attending the June 15th call. Ahead of that call, we wanted to give some updated benchmarks and clarify some points from our previous comment. 

We have continued to investigate the performance of binary serialization/deserialization formats. The following parsing speed benchmarks take the mean of 1000 iterations of each parser. As noted before, the segments array is looped through to ensure the underlying data is indeed accessible in memory.  

Format | Speed | Size
-- | -- | --
JSON | 628 | 261262
Flatbuffers (Unchecked) | <1 | 79424
Flatbuffers (Checked) | 206 | 79424
Cap'n Proto | 2 | 72176
MessagePack | 127 | 46222
ProtoBuf | 124 | 44848
CBOR (String Keys) | 457 | 188626
CBOR (Integer Keys) | 119 | 46326

A code change made a significant improvement in the Cap'n Proto numbers. For CBOR, either a string or an integer can be used as a key. The original benchmarks used strings as keys, which resulted in the lackluster numbers for CBOR. Using integers for keys in CBOR saw a significant improvement in both parsing speed and data size. 

MessagePack is still our recommended binary format for multiple reasons:
- Maintain/version a single sidecar format
- No separate Interface Description Language (IDL) to maintain
- Can write JSON to MessagePack utility with no JSON modification

Here is the ProtoBuf Interface Description Language (IDL) used to generate data access code in the above benchmarks. 

```
syntax = "proto3";
package sidecar;

message Sidecar {

    message Variantsubpaths {
        uint32 variant = 1;
        string subPath = 2;
    }

    message wmpaceinfoobject {
        uint32 version = 1;
        bool iswm = 2;
        uint32 variant = 3;
        uint32 pos = 4;
        bool firstpart = 5;
        uint32 nbpart = 6;
    }

    message Segments {
        uint64 startRange = 1;
        uint64 endRange = 2;
        wmpaceinfoobject WMPaceInfoObject = 3;
    }

    string segmentType = 1;
    repeated Variantsubpaths variantSubPaths = 2;
    repeated Segments segments = 3;
}
```

FlatBuffers and Cap'n Proto also use an IDL with similar syntax. Using any format that relies on an IDL will mean taking great care to ensure both the JSON and binary format are able to describe the same data. We had some difficulty converting sidecar JSON files to both Cap'n Proto and FlatBuffers, because those formats have strict case expectations for keys. FlatBuffers requires snake_case and Cap'n Proto strictly enforces camelCase (the `WMPaceInfo` key violates camelCase formatting). The case issue makes it not straight-forward to convert JSON sidecar files to those formats. However, ProtoBuf had no issues with the existing JSON sidecar keys casing. 

@msanmart-akamai regarding the two separate access functions in FlatBuffers, the generated accessor code from Google's FlatBuffers crate has the following comment `Callers must trust the given bytes do indeed contain a valid WMPaceInfo.` While this may only be called out in the Rust implementation, it's likely to be an issue in other languages.  More information on untrusted buffers can be found on the bottom of Google's Rust FlatBuffers implementation webpage: https://google.github.io/flatbuffers/flatbuffers_guide_use_rust.html

**Comment by joshjohnson** [comment]
I tested MessagePack performance in JavaScript, using the `@msgpack/msgpack` library (https://www.npmjs.com/package/@msgpack/msgpack).  I also found that MessagePack was faster than JSON, though still several orders of magnitude slower than FlatBuffers.

Here are updated test results from a sidecar file with 3,722 segments, representing a video that is 124 minutes long with 2 second segments.  The flatbuffers test uses 100 million iterations, because at 1,000 iterations I was only really measuring the overhead of the performance observer framework

|  | Number of operations | Amount of time | Operations per second |
| --- | --: | --: | --: |
| JSON | 10,000 | 25,992 ms | **385** |
| MessagePack | 10,000 | 13,276 ms | **753** |
| Flatbuffers | 100,000,000 | 8,679 ms | **11,522,065** |

(I have upgraded my laptop since my original tests, so the higher performance compared to my original tests is expected)

Based on this data, MessagePack parsing is about twice as efficient as JSON, but still ~15,000 times less efficient than Flatbuffers.

I suspect that the biggest efficiency benefit of Flatbuffers comes for the ability to reference an individual segment by index without first scanning/parsing the entire file.  As the number of segments increases, it becomes more and more important to avoid unnecessary processing of every segment.

**Comment by RobertLabonte** [comment]
FlatBuffers handily win speed comparisons against other serialization formats. Every benchmark done by Fastly and Akamai have shown that. The concern discussed on the June 15th meeting was around upgrade paths and the safety of using FlatBuffers generated by 3rd parties. FlatBuffers were designed for passing data between processes that are usually controlled by the same party. 

- Can fields be safely removed and or added to FlatBuffers without breaking existing implementations?
- In the event of a new specification version, can we guarantee that version 1 and version 2 of the FlatBuffer sidecar can be parsed by code generated from version 1 in all languages?

In the Rust implementation, there doesn't seem to be the ability to cherrypick a single value from the FlatBuffer. The parsing code is designed to read the whole thing at once. This means in the event of a new version of the sidecar being created, an existing implementation may not be able to parse the version key/value to know it is not supported. 

Serialization solutions like MessagePack and CBOR are designed around these concerns; while FlatBuffers, from our research, aren't designed for these concerns. We fully agree, going with FlatBuffers will be the most performant solution, but they could create a dead end for adding additional features to the specification down the road.

**Comment by lpiron** [comment]
Proposal is to go with CBOR (integer keys) for WMPaceInfo data as part of the sidecar file and the headers between the origin and the edge. 
From the encoder to the origin, either CBOR or JSON (both have advantages and disadvantages depending of the use case)
The watermarking token will also migrate to CBOR (integer keys)

**Comment by lpiron** [comment]
Implemented in the updated version available [here](https://dashif.org/docs/IOP-Guidelines/DASH-IF-CTS-00XX-AB-Watermarking-0.9.pdf) for [review](https://dashif.org/guidelines/others/#dash-if-candidate-technical-specification-dash-if-forensic-ab-watermarking)
