### ISSUE TITLE
Use of segduration as an alternative to WMPaceinfo

### ISSUE THREAD

**Issue by nicoweil** [Dash-Industry-Forum/Watermarking#2]
It seems like section 5.4.4 allows to apply A/B watermarking without any WMPaceinfo information, and that this section is desdigned to cover legacy CDN implementations. Can we precise why this section appears in the spec, and be very explicit about the fact that the absence of WMPaceinfo is due to the legacy nature of this approach? As it stands, it can be understood as "by the way, if you don't want to use WMPaceinfo, just do this".

**Comment by lpiron** [comment]
Clarify that segduration support not encouraged and forward-looking solution is WMPaceInfo.

**Comment by GwenSynamedia** [comment]
Latest edits of the document have removed §5.4.4 altogether.
The DASH IF spec does not specify any requirement on how to manage segduration
The person implementing the spec is simply informed that this field exists in the WM token because the same WM token generator may serve DASH-If and non DASH-If compliant CDNs.

Issue can be closed I believe

**Comment by lpiron** [comment]
Closing as the text has been updated
