### ISSUE TITLE
variantId translation into variantPath

### ISSUE THREAD

**Issue by nicoweil** [Dash-Industry-Forum/Watermarking#30]
Section 5.3 says
When addressing content, variantId shall be translated into variantPath as follows: variantPath = ${variantId} followed by ‘/’ or ‘.’

I believe it should just say 
variantPath = ${variantId} followed by ‘/’
because if you do variantPath = ${variantId}+'.' it means that '.' needs to be part the segment filename. 

If this is a use case that we really want to allow, we have to be explicit about it, and specify that it should be included in the CDN configuration (as this is a different approach than adding a sub-path in forward requests).

**Comment by GwenSynamedia** [comment]
Let's say that the segment URI is formed as `http(s)://hostname/path/segmentname`

The main conventions for A/B WM addressing that I am aware of are
`http(s)://hostname/path/a/segmentname` and `http(s)://hostname/path/b/segmentname`
vs.
`http(s)://hostname/path/segmentname` and `http(s)://hostname/path/b/segmentname`
vs.
`http(s)://hostname/path/segmentname` and `http(s)://hostname/path/b.segmentname`

The "empty" A variant is intended to provide a straightforward fallback e.g. when deactivating the sequencing logic at the edge.
This is the rationale of the current wording.

It would indeed not hurt clarity to specify the variant separator in the CDN configuration and limit it to `/` or `.` for the time being.
In practice, the CDN will need to be configured to interoperate with the preferred convention of the JiTP / Origin.

**Potential alternate wording**

When addressing content, `variantId` shall be translated into `variantPath` as follows:
- `variantPath` = `${variantId}` followed by `${variantSeparator}`
- As an exception, if `${variantId}` is `a` or `0` then `${variantPath}` may be empty

The `variantSeparator` to be used by the CDN shall be configured according to the characteristics of the JIT¨/Origin it interfaces with. The only `variantSeparator` supported in this specification are  the dot character `.` and the slash character `/`.

**Comment by GwenSynamedia** [comment]
Quick summary after the DASH IF call tonight
- JiTP usually want to have full flexibility on the filename convention. Supporting `.` convention (third bullet point in my previous message) breaks this flexibility.
- The `.` convention is naturally supported for "passthrough" JiTP. However, it significantly raise complexity for "transforming" JiTP. In any case, clarification will be added in the text about the expectation wrt. ingress vs. egress naming transformations.
- Based on the recollection of attendees, the `.` convention may be historically due to legacy Origins that could only expose a single publication endpoints for both Variants.

The working group is currently considering deprecating the support of this convention for the sake of simplicity. All relevant stakeholders are to check internally if there are strong constraints for supporting the `.` convention.

**Comment by GwenSynamedia** [comment]
While this is still in discussion internally on my side, one of my colleagues reminded me that these naming conventions originate in part from Akamai native watermarking logic.
https://techdocs.akamai.com/adaptive-media-delivery/docs/source-content-preprocessing
Please check in particular the section about audio and video
https://techdocs.akamai.com/adaptive-media-delivery/docs/source-content-preprocessing#are-you-using-separate-audio-and-video-segments
@wilaw @msanmart-akamai you may want to provide your view on this issue

**Comment by wilaw** [comment]
@GwenSynamedia  - since Akamai supports both naming conventions and the proposal is to restrict to only the / syntax, I'm fine with it. I'd like @msanmart-akamai to confirm that.

The constituents we should be asking are the "_... legacy Origins that could only expose a single publication endpoints for both Variants._". They risk being cut out by this change. Who owns those 'legacy' origins?

**Comment by lpiron** [comment]
We remove the . option

**Comment by lpiron** [comment]
Closing as this is integrated in the published document
